#!/usr/bin/env python3
"""
NNUE Trainer for Prometheus Chess Engine.
Trains a HalfKP -> 256 -> 32 -> 1 network from binary training data.
Outputs quantized weights in the format expected by nn.rs.
"""

import struct
import os
import sys
import numpy as np
import time
import math
import random

# Network architecture (must match nn.rs)
HALFKP_FEATURES = 40960  # 64 * 10 * 64
HIDDEN_SIZE = 256
L1_SIZE = 32

# Quantization constants
FT_QUANT = 64       # Feature transformer quantization (weights stored as i16)
L1_QUANT = 64       # Layer 1 quantization
OUTPUT_QUANT = 16   # Output quantization


def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-np.clip(x, -20, 20)))


def load_training_data(path, max_positions=None):
    """Load binary training data generated by generate_training_data.py"""
    positions = []
    
    with open(path, 'rb') as f:
        data = f.read()
    
    offset = 0
    count = 0
    
    while offset < len(data):
        if max_positions and count >= max_positions:
            break
            
        try:
            # Read white features
            nw = struct.unpack_from('<H', data, offset)[0]
            offset += 2
            wf = []
            for _ in range(nw):
                idx = struct.unpack_from('<H', data, offset)[0]
                offset += 2
                if idx < HALFKP_FEATURES:
                    wf.append(idx)
            
            # Read black features
            nb = struct.unpack_from('<H', data, offset)[0]
            offset += 2
            bf = []
            for _ in range(nb):
                idx = struct.unpack_from('<H', data, offset)[0]
                offset += 2
                if idx < HALFKP_FEATURES:
                    bf.append(idx)
            
            # Read score, result, stm
            score = struct.unpack_from('<h', data, offset)[0]
            offset += 2
            result = struct.unpack_from('<f', data, offset)[0]
            offset += 4
            stm = struct.unpack_from('<B', data, offset)[0]
            offset += 1
            
            positions.append((wf, bf, score, result, stm))
            count += 1
            
        except struct.error:
            break
    
    print(f"Loaded {count} positions from {path}")
    return positions


class NNUE:
    """Simple NNUE network with manual gradient computation."""
    
    def __init__(self):
        # Feature transformer: HALFKP_FEATURES -> HIDDEN_SIZE
        # Initialize with small random values
        scale_ft = 0.01
        self.ft_weights = np.random.randn(HALFKP_FEATURES, HIDDEN_SIZE).astype(np.float32) * scale_ft
        self.ft_biases = np.zeros(HIDDEN_SIZE, dtype=np.float32)
        
        # Layer 1: 2*HIDDEN_SIZE -> L1_SIZE
        scale_l1 = math.sqrt(2.0 / (2 * HIDDEN_SIZE))
        self.l1_weights = np.random.randn(2 * HIDDEN_SIZE, L1_SIZE).astype(np.float32) * scale_l1
        self.l1_biases = np.zeros(L1_SIZE, dtype=np.float32)
        
        # Output: L1_SIZE -> 1
        scale_out = math.sqrt(2.0 / L1_SIZE)
        self.out_weights = np.random.randn(L1_SIZE).astype(np.float32) * scale_out
        self.out_bias = np.float32(0.0)
        
        # Adam optimizer state
        self._init_adam()
    
    def _init_adam(self):
        self.t = 0
        self.m = {}
        self.v = {}
        for name in ['ft_weights', 'ft_biases', 'l1_weights', 'l1_biases', 'out_weights', 'out_bias']:
            param = getattr(self, name)
            self.m[name] = np.zeros_like(param)
            self.v[name] = np.zeros_like(param)
    
    def clipped_relu(self, x):
        """CReLU: clamp to [0, 1] (will be [0, 127] after quantization)"""
        return np.clip(x, 0, 1)
    
    def forward_batch(self, batch):
        """
        Forward pass for a batch of positions.
        Returns predictions and cached intermediates for backprop.
        """
        batch_size = len(batch)
        
        # Compute accumulator outputs
        acc_white = np.tile(self.ft_biases, (batch_size, 1))  # (B, HIDDEN)
        acc_black = np.tile(self.ft_biases, (batch_size, 1))  # (B, HIDDEN)
        
        for i, (wf, bf, score, result, stm) in enumerate(batch):
            for idx in wf:
                acc_white[i] += self.ft_weights[idx]
            for idx in bf:
                acc_black[i] += self.ft_weights[idx]
        
        # Build the input based on side to move
        # stm=1 -> white to move -> [white_acc, black_acc]
        # stm=0 -> black to move -> [black_acc, white_acc]
        stm_arr = np.array([b[4] for b in batch])
        
        us = np.where(stm_arr[:, None] == 1, acc_white, acc_black)
        them = np.where(stm_arr[:, None] == 1, acc_black, acc_white)
        
        # CReLU on accumulator
        us_clamped = self.clipped_relu(us)
        them_clamped = self.clipped_relu(them)
        
        # Concatenate
        hidden_input = np.concatenate([us_clamped, them_clamped], axis=1)  # (B, 2*HIDDEN)
        
        # Layer 1
        l1_pre = hidden_input @ self.l1_weights + self.l1_biases  # (B, L1)
        l1_post = self.clipped_relu(l1_pre)
        
        # Output
        output = l1_post @ self.out_weights + self.out_bias  # (B,)
        
        cache = {
            'acc_white': acc_white,
            'acc_black': acc_black,
            'us_clamped': us_clamped,
            'them_clamped': them_clamped,
            'hidden_input': hidden_input,
            'l1_pre': l1_pre,
            'l1_post': l1_post,
            'stm_arr': stm_arr,
        }
        
        return output, cache
    
    def backward_batch(self, batch, output, cache, targets):
        """Compute gradients for the batch."""
        batch_size = len(batch)
        
        # dL/d_output - MSE gradient
        d_output = 2.0 * (output - targets) / batch_size  # (B,)
        
        # Output layer gradients
        d_out_weights = cache['l1_post'].T @ d_output  # (L1,)
        d_out_bias = np.sum(d_output)
        
        # d_l1_post
        d_l1_post = np.outer(d_output, self.out_weights)  # (B, L1)
        
        # CReLU backward for L1
        d_l1_pre = d_l1_post * ((cache['l1_pre'] > 0) & (cache['l1_pre'] < 1)).astype(np.float32)
        
        # L1 weight gradients
        d_l1_weights = cache['hidden_input'].T @ d_l1_pre  # (2*HIDDEN, L1)
        d_l1_biases = np.sum(d_l1_pre, axis=0)  # (L1,)
        
        # d_hidden_input
        d_hidden = d_l1_pre @ self.l1_weights.T  # (B, 2*HIDDEN)
        
        # Split into us and them
        d_us_clamped = d_hidden[:, :HIDDEN_SIZE]
        d_them_clamped = d_hidden[:, HIDDEN_SIZE:]
        
        # CReLU backward for accumulator
        stm_arr = cache['stm_arr']
        acc_white = cache['acc_white']
        acc_black = cache['acc_black']
        
        us_raw = np.where(stm_arr[:, None] == 1, acc_white, acc_black)
        them_raw = np.where(stm_arr[:, None] == 1, acc_black, acc_white)
        
        d_us = d_us_clamped * ((us_raw > 0) & (us_raw < 1)).astype(np.float32)
        d_them = d_them_clamped * ((them_raw > 0) & (them_raw < 1)).astype(np.float32)
        
        # Map back to white/black accumulators
        d_acc_white = np.where(stm_arr[:, None] == 1, d_us, d_them)
        d_acc_black = np.where(stm_arr[:, None] == 1, d_them, d_us)
        
        # Feature transformer gradients (sparse)
        d_ft_biases = np.sum(d_acc_white + d_acc_black, axis=0)
        
        # Sparse FT weight update
        d_ft_weights = np.zeros_like(self.ft_weights)
        for i, (wf, bf, _, _, _) in enumerate(batch):
            for idx in wf:
                d_ft_weights[idx] += d_acc_white[i]
            for idx in bf:
                d_ft_weights[idx] += d_acc_black[i]
        
        return {
            'ft_weights': d_ft_weights,
            'ft_biases': d_ft_biases,
            'l1_weights': d_l1_weights,
            'l1_biases': d_l1_biases,
            'out_weights': d_out_weights,
            'out_bias': d_out_bias,
        }
    
    def adam_update(self, grads, lr=0.001, beta1=0.9, beta2=0.999, eps=1e-8, wd=1e-6):
        """Adam optimizer step with weight decay."""
        self.t += 1
        
        for name in grads:
            param = getattr(self, name)
            grad = grads[name]
            
            # Weight decay
            if name not in ('ft_biases', 'l1_biases', 'out_bias'):
                grad = grad + wd * param
            
            self.m[name] = beta1 * self.m[name] + (1 - beta1) * grad
            self.v[name] = beta2 * self.v[name] + (1 - beta2) * (grad ** 2)
            
            m_hat = self.m[name] / (1 - beta1 ** self.t)
            v_hat = self.v[name] / (1 - beta2 ** self.t)
            
            param -= lr * m_hat / (np.sqrt(v_hat) + eps)
            setattr(self, name, param)
    
    def save_quantized(self, path):
        """
        Save the network in the binary format expected by nn.rs.
        
        Layout (must match Network struct in nn.rs):
        - FeatureTransformer:
          - weights: [i16; HALFKP_FEATURES * HIDDEN_SIZE]
          - biases: [i16; HIDDEN_SIZE]
        - layer1_weights: [i8; 2 * HIDDEN_SIZE * L1_SIZE]
        - layer1_biases: [i32; L1_SIZE]
        - output_weights: [i8; L1_SIZE]
        - output_bias: i32
        """
        with open(path, 'wb') as f:
            # Feature transformer weights (i16, scaled by FT_QUANT)
            ft_w = np.clip(self.ft_weights * FT_QUANT, -32768, 32767).astype(np.int16)
            f.write(ft_w.tobytes())
            
            # Feature transformer biases (i16, scaled by FT_QUANT)
            ft_b = np.clip(self.ft_biases * FT_QUANT, -32768, 32767).astype(np.int16)
            f.write(ft_b.tobytes())
            
            # Layer 1 weights (i8, scaled by L1_QUANT)
            l1_w = np.clip(self.l1_weights * L1_QUANT, -128, 127).astype(np.int8)
            f.write(l1_w.tobytes())
            
            # Layer 1 biases (i32, scaled by FT_QUANT * L1_QUANT)
            l1_b = np.clip(self.l1_biases * FT_QUANT * L1_QUANT, -2147483648, 2147483647).astype(np.int32)
            f.write(l1_b.tobytes())
            
            # Output weights (i8, scaled by OUTPUT_QUANT)
            out_w = np.clip(self.out_weights * OUTPUT_QUANT, -128, 127).astype(np.int8)
            f.write(out_w.tobytes())
            
            # Output bias (i32, scaled by OUTPUT_QUANT * L1_QUANT)
            out_b = np.int32(np.clip(self.out_bias * OUTPUT_QUANT * L1_QUANT, -2147483648, 2147483647))
            f.write(out_b.tobytes())
        
        file_size = os.path.getsize(path)
        print(f"Saved quantized network to {path} ({file_size / 1024 / 1024:.1f} MB)")


def cp_to_target(cp, result, blend=0.5):
    """
    Convert centipawn score to training target.
    Blend between sigmoid of cp and game result.
    Target is in centipawn-like scale.
    """
    # Sigmoid of cp/400 gives win probability
    win_prob = sigmoid(cp / 400.0)
    # Blend with game result
    blended = blend * win_prob + (1 - blend) * result
    # Convert back to centipawn scale
    # We want the network to output centipawns from STM perspective
    return cp


def train(data_path, output_path, epochs=80, batch_size=8192, lr=0.001):
    """Train the NNUE network."""
    
    print("Loading training data...")
    positions = load_training_data(data_path)
    
    if len(positions) < 100:
        print("Not enough training data! Need at least 100 positions.")
        return
    
    print(f"Training on {len(positions)} positions")
    
    net = NNUE()
    
    # Prepare targets (centipawns from side-to-move perspective)
    targets_list = []
    for wf, bf, score, result, stm in positions:
        # Score is from white's perspective, convert to STM perspective
        cp = score if stm == 1 else -score
        # Scale to reasonable range for the network
        targets_list.append(cp / 400.0)  # Normalize
    
    best_loss = float('inf')
    
    for epoch in range(epochs):
        # Shuffle
        indices = list(range(len(positions)))
        random.shuffle(indices)
        
        total_loss = 0.0
        num_batches = 0
        
        # Learning rate schedule
        if epoch < 10:
            current_lr = lr * (epoch + 1) / 10  # Warmup
        elif epoch > 60:
            current_lr = lr * 0.1
        elif epoch > 40:
            current_lr = lr * 0.3
        else:
            current_lr = lr
        
        for batch_start in range(0, len(positions), batch_size):
            batch_end = min(batch_start + batch_size, len(positions))
            batch_indices = indices[batch_start:batch_end]
            
            batch = [positions[i] for i in batch_indices]
            batch_targets = np.array([targets_list[i] for i in batch_indices], dtype=np.float32)
            
            # Forward
            output, cache = net.forward_batch(batch)
            
            # Loss (MSE)
            loss = np.mean((output - batch_targets) ** 2)
            total_loss += loss
            num_batches += 1
            
            # Backward
            grads = net.backward_batch(batch, output, cache, batch_targets)
            
            # Update
            net.adam_update(grads, lr=current_lr)
        
        avg_loss = total_loss / max(num_batches, 1)
        
        if (epoch + 1) % 5 == 0 or epoch == 0:
            print(f"Epoch {epoch+1}/{epochs} | Loss: {avg_loss:.6f} | LR: {current_lr:.6f}")
        
        # Save best model
        if avg_loss < best_loss:
            best_loss = avg_loss
            net.save_quantized(output_path)
    
    print(f"\nTraining complete! Best loss: {best_loss:.6f}")
    print(f"Network saved to: {output_path}")


def main():
    data_path = "/home/ansh/prometheus/training_data/training.bin"
    output_path = "/home/ansh/prometheus/prometheus.nnue"
    
    if not os.path.exists(data_path):
        print(f"Training data not found at {data_path}")
        print("Run generate_training_data.py first!")
        return
    
    train(data_path, output_path, epochs=80, batch_size=8192, lr=0.001)


if __name__ == "__main__":
    main()
